# Hero create
HERO_CREATE_MONEY = 0.00
HERO_CREATE_ART_MONEY = 0.00
HERO_CREATE_HP = 30
HERO_CREATE_CAPACITY = 30

HERO_CREATE_STRENGTH = 3
HERO_CREATE_DEXTERITY = 3
HERO_CREATE_INTUITION = 3
HERO_CREATE_HEALTH = 3

HERO_CREATE_SWORDS = 0
HERO_CREATE_AXES = 0
HERO_CREATE_KNIVES = 0
HERO_CREATE_CLUBS = 0
HERO_CREATE_SHIELDS = 0

HERO_CREATE_NUMBER_OF_ABILITIES = 0
HERO_CREATE_NUMBER_OF_SKILLS = 0
HERO_CREATE_NUMBER_OF_PARAMETERS = 0

HERO_CREATE_STRIKE_COUNT = 1
HERO_CREATE_BLOCK_COUNT = 2

HERO_CREATE_LOCATION_ON_THE_ISLAND = '20|20|0'
# End hero create

# Modifier coefficient
MODIFIER_COEFFICIENT_DAMAGE_MIN = 2
MODIFIER_COEFFICIENT_DAMAGE_MAX = 3

MODIFIER_COEFFICIENT_ACCURACY = 2
MODIFIER_COEFFICIENT_DODGE = 2.5
MODIFIER_COEFFICIENT_DEVASTATE = 2.5
MODIFIER_COEFFICIENT_DURABILITY = 2

MODIFIER_COEFFICIENT_HP = 10

MODIFIER_COEFFICIENT_CAPACITY = 10
# End modifier coefficient

# Bot create
BOT_CREATE_STRIKE_COUNT = 1
BOT_CREATE_BLOCK_COUNT = 2
# End bot create

# Url reverse dafault page
URL_REVERSE_404 = 'hero'
# End url reverse default page

# Things
THINGS_COUNT_OF_RINGS = 4
THINGS_COUNT_OF_ARMS = 2
# End things

# Island
ISLAND_MOVE_DELAY = 15
ISLAND_PART_DIMENSION = 30
# End island

# Combat create
COMBAT_CREATE_TIME_OUT = 60
# End combat create

# Combat range on strike
COMBAT_RANGE_ACCURACY = 500
COMBAT_RANGE_DEVASTATE = 500
COMBAT_RANGE_BLOCK_BREAK = 1000
COMBAT_RANGE_ARMOR_BREAK = 1000
COMBAT_RANGE_DAMAGE = 10
# End combat range on strike

# Hp regeneration
HP_REGENERATION_DELAY = 1500.0
# End hp regeneration